/*
 * Feather Amalgamation
 * 
 * This file includes all feather C source files into a single translation unit.
 * It enables `go install` support by letting cgo compile the C core directly.
 */

/* Utility modules first (no dependencies) */
#include "./src/charclass.c"
#include "./src/index_parse.c"
#include "./src/level_parse.c"
#include "./src/namespace_util.c"

/* Core modules */
#include "./src/arena.c"
#include "./src/memory.c"
#include "./src/glob.c"
#include "./src/parse.c"
#include "./src/resolve.c"
#include "./src/interp.c"
#include "./src/eval.c"
#include "./src/trace.c"
#include "./src/var.c"

/* Builtins */
#include "./src/builtin_append.c"
#include "./src/builtin_apply.c"
#include "./src/builtin_break.c"
#include "./src/builtin_catch.c"
#include "./src/builtin_concat.c"
#include "./src/builtin_continue.c"
#include "./src/builtin_dict.c"
#include "./src/builtin_error.c"
#include "./src/builtin_eval.c"
#include "./src/builtin_expr.c"
#include "./src/builtin_for.c"
#include "./src/builtin_foreach.c"
#include "./src/builtin_format.c"
#include "./src/builtin_lmap.c"
#include "./src/builtin_lassign.c"
#include "./src/builtin_linsert.c"
#include "./src/builtin_global.c"
#include "./src/builtin_if.c"
#include "./src/builtin_incr.c"
#include "./src/builtin_info.c"
#include "./src/builtin_join.c"
#include "./src/builtin_lappend.c"
#include "./src/builtin_lindex.c"
#include "./src/builtin_list.c"
#include "./src/builtin_llength.c"
#include "./src/builtin_lrange.c"
#include "./src/builtin_lreplace.c"
#include "./src/builtin_lrepeat.c"
#include "./src/builtin_lreverse.c"
#include "./src/builtin_lsearch.c"
#include "./src/builtin_lset.c"
#include "./src/builtin_lsort.c"
#include "./src/builtin_mathfunc.c"
#include "./src/builtin_namespace.c"
#include "./src/builtin_proc.c"
#include "./src/builtin_rename.c"
#include "./src/builtin_return.c"
#include "./src/builtin_scan.c"
#include "./src/builtin_set.c"
#include "./src/builtin_split.c"
#include "./src/builtin_string.c"
#include "./src/builtin_subst.c"
#include "./src/builtin_switch.c"
#include "./src/builtin_tailcall.c"
#include "./src/builtin_throw.c"
#include "./src/builtin_trace.c"
#include "./src/builtin_try.c"
#include "./src/builtin_unset.c"
#include "./src/builtin_uplevel.c"
#include "./src/builtin_upvar.c"
#include "./src/builtin_variable.c"
#include "./src/builtin_while.c"

/* Host operations (provides feather_get_ops and default_ops) */
#include "./src/host.c"
