/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/feather-lang/feather/cmd/libfeather */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 7 "exports.go"

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Callback type for custom commands registered from C
typedef int (*FeatherCommandCallback)(void *userData, int argc, char **argv, char **result, char **error);

// Wrapper function to call C callback from Go
static inline int callCCallback(FeatherCommandCallback cb, void *userData, int argc, char **argv, char **result, char **error) {
    return cb(userData, argc, argv, result, error);
}

// Foreign type callbacks
typedef void* (*FeatherForeignNewFunc)(void *userData);
typedef int (*FeatherForeignInvokeFunc)(void *instance, const char *method, int argc, char **argv, char **result, char **error);
typedef void (*FeatherForeignDestroyFunc)(void *instance);

// Wrapper functions for foreign type callbacks
static inline void* callForeignNew(FeatherForeignNewFunc fn, void *userData) {
    return fn(userData);
}

static inline int callForeignInvoke(FeatherForeignInvokeFunc fn, void *instance, const char *method, int argc, char **argv, char **result, char **error) {
    return fn(instance, method, argc, argv, result, error);
}

static inline void callForeignDestroy(FeatherForeignDestroyFunc fn, void *instance) {
    fn(instance);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern size_t FeatherNew(void);
extern void FeatherClose(size_t interp);
extern int FeatherEval(size_t interp, char* script, size_t length, size_t* result);
extern int FeatherCall(size_t interp, char* cmd, int argc, size_t* argv, size_t* result);
extern size_t FeatherString(size_t interp, char* s, size_t length);
extern size_t FeatherInt(size_t interp, int64_t val);
extern size_t FeatherDouble(size_t interp, double val);
extern size_t FeatherList(size_t interp, int argc, size_t* items);
extern char* FeatherGetString(size_t obj, size_t interp, size_t* length);
extern int FeatherGetInt(size_t obj, size_t interp, int64_t* out);
extern int FeatherGetDouble(size_t obj, size_t interp, double* out);
extern int FeatherGetList(size_t interp, size_t obj, int* argc, size_t** items);
extern void FeatherRetain(size_t interp, size_t obj);
extern void FeatherRelease(size_t interp, size_t obj);
extern void FeatherFreeString(char* s);
extern size_t FeatherStringLength(size_t obj, size_t interp);
extern int FeatherStringByteAt(size_t obj, size_t interp, size_t index);
extern size_t FeatherStringSlice(size_t interp, size_t str, size_t start, size_t end);
extern size_t FeatherStringConcat(size_t interp, size_t a, size_t b);
extern int FeatherStringCompare(size_t a, size_t b, size_t interp);
extern int FeatherStringMatch(size_t pattern, size_t str, size_t interp);
extern size_t FeatherListLength(size_t obj, size_t interp);
extern size_t FeatherListAt(size_t interp, size_t list, size_t index);
extern size_t FeatherListSlice(size_t interp, size_t list, size_t first, size_t last);
extern size_t FeatherListPush(size_t interp, size_t list, size_t item);
extern size_t FeatherListSet(size_t interp, size_t list, size_t index, size_t value);
extern size_t FeatherDict(size_t interp);
extern size_t FeatherDictSize(size_t obj, size_t interp);
extern size_t FeatherDictGet(size_t interp, size_t dict, size_t key);
extern size_t FeatherDictSet(size_t interp, size_t dict, size_t key, size_t value);
extern int FeatherDictExists(size_t dict, size_t key, size_t interp);
extern size_t FeatherDictKeys(size_t interp, size_t dict);
extern void FeatherSetVar(size_t interp, char* name, size_t val);
extern size_t FeatherGetVar(size_t interp, char* name);
extern int FeatherRegisterCommand(size_t interp, char* name, FeatherCommandCallback callback, void* userData);
extern int FeatherRegisterForeign(size_t interp, char* typeName, FeatherForeignNewFunc newFn, FeatherForeignInvokeFunc invokeFn, FeatherForeignDestroyFunc destroyFn, void* userData);

#ifdef __cplusplus
}
#endif
