#include "host.h"
#include "feather.h"

static FeatherHostOps default_ops = {
    .frame = {
        .push = feather_host_frame_push,
        .pop = feather_host_frame_pop,
        .level = feather_host_frame_level,
        .set_active = feather_host_frame_set_active,
        .size = feather_host_frame_size,
        .info = feather_host_frame_info,
        .set_namespace = feather_host_frame_set_namespace,
        .get_namespace = feather_host_frame_get_namespace,
        .set_line = feather_host_frame_set_line,
        .get_line = feather_host_frame_get_line,
        .set_lambda = feather_host_frame_set_lambda,
        .get_lambda = feather_host_frame_get_lambda,
    },
    .var = {
        .get = feather_host_var_get,
        .set = feather_host_var_set,
        .unset = feather_host_var_unset,
        .exists = feather_host_var_exists,
        .link = feather_host_var_link,
        .link_ns = feather_host_var_link_ns,
        .names = feather_host_var_names,
        .is_link = feather_host_var_is_link,
        .resolve_link = feather_host_var_resolve_link,
    },
    .ns = {
        .create = feather_host_ns_create,
        .delete = feather_host_ns_delete,
        .exists = feather_host_ns_exists,
        .current = feather_host_ns_current,
        .parent = feather_host_ns_parent,
        .children = feather_host_ns_children,
        .get_var = feather_host_ns_get_var,
        .set_var = feather_host_ns_set_var,
        .var_exists = feather_host_ns_var_exists,
        .unset_var = feather_host_ns_unset_var,
        .get_command = feather_host_ns_get_command,
        .set_command = feather_host_ns_set_command,
        .delete_command = feather_host_ns_delete_command,
        .list_commands = feather_host_ns_list_commands,
        .get_exports = feather_host_ns_get_exports,
        .set_exports = feather_host_ns_set_exports,
        .is_exported = feather_host_ns_is_exported,
        .copy_command = feather_host_ns_copy_command,
    },
    .string = {
        .byte_at = feather_host_string_byte_at,
        .byte_length = feather_host_string_byte_length,
        .slice = feather_host_string_slice,
        .concat = feather_host_string_concat,
        .compare = feather_host_string_compare,
        .equal = feather_host_string_equal,
        .match = feather_host_string_match,
        .regex_match = feather_host_string_regex_match,
        .builder_new = feather_host_string_builder_new,
        .builder_append_byte = feather_host_string_builder_append_byte,
        .builder_append_obj = feather_host_string_builder_append_obj,
        .builder_finish = feather_host_string_builder_finish,
        .intern = feather_host_string_intern,
    },
    .rune = {
        .length = feather_host_rune_length,
        .at = feather_host_rune_at,
        .range = feather_host_rune_range,
        .to_upper = feather_host_rune_to_upper,
        .to_lower = feather_host_rune_to_lower,
        .fold = feather_host_rune_fold,
    },
    .list = {
        .is_nil = feather_host_list_is_nil,
        .create = feather_host_list_create,
        .from = feather_host_list_from,
        .push = feather_host_list_push,
        .pop = feather_host_list_pop,
        .unshift = feather_host_list_unshift,
        .shift = feather_host_list_shift,
        .length = feather_host_list_length,
        .at = feather_host_list_at,
        .slice = feather_host_list_slice,
        .set_at = feather_host_list_set_at,
        .splice = feather_host_list_splice,
        .sort = feather_host_list_sort,
    },
    .dict = {
        .create = feather_host_dict_create,
        .is_dict = feather_host_dict_is_dict,
        .from = feather_host_dict_from,
        .get = feather_host_dict_get,
        .set = feather_host_dict_set,
        .exists = feather_host_dict_exists,
        .remove = feather_host_dict_remove,
        .size = feather_host_dict_size,
        .keys = feather_host_dict_keys,
        .values = feather_host_dict_values,
    },
    .integer = {
        .create = feather_host_integer_create,
        .get = feather_host_integer_get,
    },
    .dbl = {
        .create = feather_host_dbl_create,
        .get = feather_host_dbl_get,
        .classify = feather_host_dbl_classify,
        .format = feather_host_dbl_format,
        .math = feather_host_dbl_math,
    },
    .interp = {
        .set_result = feather_host_interp_set_result,
        .get_result = feather_host_interp_get_result,
        .reset_result = feather_host_interp_reset_result,
        .set_return_options = feather_host_interp_set_return_options,
        .get_return_options = feather_host_interp_get_return_options,
        .get_script = feather_host_interp_get_script,
        .set_script = feather_host_interp_set_script,
    },
    .bind = {
        .unknown = feather_host_bind_unknown,
    },
    .foreign = {
        .is_foreign = feather_host_foreign_is_foreign,
        .type_name = feather_host_foreign_type_name,
        .string_rep = feather_host_foreign_string_rep,
        .methods = feather_host_foreign_methods,
        .invoke = feather_host_foreign_invoke,
        .destroy = feather_host_foreign_destroy,
    },
};

const FeatherHostOps *feather_get_ops(const FeatherHostOps *ops) {
    return ops ? ops : &default_ops;
}
